### ISSUE TITLE
add new models

### ISSUE THREAD

**Issue by tylerfordML** [Hydrospheredata/spark-ml-serving#20]
how would you add a new model to be used ? meaning, i am trying to run a pipeline that is using a regex-tokenizer. I saw in the code that you have a regular tokenizer, but not a reg-ex tokenizer. so my question is this, I can add that class and compile the code successfully, however, how do I get the the run-time to compile of that local code instead of the baked repository. does that make sense ?

**Comment by KineticCookie** [comment]
Hello.
Thank you for your feedback.

1. Thanks for poining out absent model. I'll add a `org.apache.spark.ml.feature.RegexTokenizer` support in next release.
2. Yes, you can fork this repo and implement other things, but in this case, you will need to make changes in runtime. As I understand, you are referring to https://github.com/Hydrospheredata/hydro-serving-spark runtime, then you also need to fork it and change it's dependency to your library.

**Comment by KineticCookie** [comment]
Fixed in https://github.com/Hydrospheredata/spark-ml-serving/releases/tag/v0.2.2
