### ISSUE TITLE
Add suport for Gradient-boosted tree classifier

### ISSUE THREAD

**Issue by alberskib** [Hydrospheredata/spark-ml-serving#22]
Please implement support for:
https://spark.apache.org/docs/2.2.0/ml-classification-regression.html#gradient-boosted-tree-classifier

**Comment by KineticCookie** [comment]
Hello @alberskib 
Thank you for feedback!

We already implemented the local version of [GBTClassificationModel](https://github.com/Hydrospheredata/spark-ml-serving/blob/master/spark-2_2/src/main/scala/io/hydrosphere/spark_ml_serving/classification/LocalGBTClassificationModel.scala)

Did you encounter any problems regarding this model?

**Comment by alberskib** [comment]
Hello @KineticCookie 
I used old version of lib that do not support GBTClassification by mistake.

Thanks for help and great lib.
